server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kurly?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: whdgns1002@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # update create none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  level:
    org:
      hibernate:
        type: trace
elasticsearch:
  host: 127.0.0.1
  port: 9200


kafka:
  serverIP: 44.209.59.22:9092